### PR TITLE
Update README info about dependency from 'six'

### PR DESCRIPTION
**Pull request by ch-t**
requested by [#14](https://github.com/reportportal/agent-Python-RobotFramework/issues/14)
'six' library exists in requirements list. PR updates info about dependencies in README.
I propose to use some tool like this https://requires.io for dependency monitoring in future.

### CODE REVIEW

**Comment by ch-t** [comment]
Retry Deepcode

**Comment by ch-t** [comment]
Retry Deepcode

**Comment by krasoffski** [comment]
`six` is part deps of `python-client` for report portal. Thus, even when robot framework did not have `six` as dep it was intalled as dep for `python-client`

**Comment by ch-t** [comment]
from setup.py
`requirements = [
    "reportportal-client>=3.0.0",
    "six",
]`

@krasoffski, also, documentation was requested by you in [ #14](https://github.com/reportportal/agent-Python-RobotFramework/issues/14) discussion.

**Pull request merged**
